name: WebGame CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:

  build-and-test:

    name: Build and Unit Test

    runs-on: ubuntu-24.04

    steps:

      # ==========================================
      # 1. Checkout source code
      # ==========================================
      - name: Checkout source code
        uses: actions/checkout@v5

      # ==========================================
      # 2. Setup JDK 21
      # ==========================================
      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      # ==========================================
      # 3. Install Ant
      # ==========================================
      - name: Install Ant
        run: |
          sudo apt-get update
          sudo apt-get install -y ant

      # ==========================================
      # 4. Setup Tomcat 10.1.57
      # ==========================================
      - name: Setup Tomcat 10.1.57
        run: |
          wget -q https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.57/bin/apache-tomcat-10.1.57.tar.gz
          tar -xzf apache-tomcat-10.1.57.tar.gz
          echo "CATALINA_HOME=$GITHUB_WORKSPACE/apache-tomcat-10.1.57" >> $GITHUB_ENV

      # ==========================================
      # 5. Check Java
      # ==========================================
      - name: Check Java version
        run: java -version

      # ==========================================
      # 6. Check Ant
      # ==========================================
      - name: Check Ant version
        run: ant -version

      # ==========================================
      # 7. Check Tomcat
      # ==========================================
      - name: Check Tomcat
        run: |
          echo "Tomcat home: $CATALINA_HOME"
          ls -la "$CATALINA_HOME"

        
      - name: Check NetBeans CopyLibs
        run: |
            ls -lh "$GITHUB_WORKSPACE/lib/"

      # ==========================================
      # 8. Clean project
      # ==========================================
      - name: Clean project
        run: |
            ant \
            -Dj2ee.server.home="$CATALINA_HOME" \
            -Dlibs.CopyLibs.classpath="$GITHUB_WORKSPACE/lib/org-netbeans-modules-java-j2seproject-copylibstask.jar" \
            clean

      # ==========================================
      # 9. Unit Test
      # ==========================================
      - name: Run unit tests
        run: |
            ant \
            -Dj2ee.server.home="$CATALINA_HOME" \
            -Dlibs.CopyLibs.classpath="$GITHUB_WORKSPACE/lib/org-netbeans-modules-java-j2seproject-copylibstask.jar" \
            test

      # ==========================================
      # 10. Build WAR
      # ==========================================
      - name: Build WAR
        run: |
            ant \
            -Dj2ee.server.home="$CATALINA_HOME" \
            -Dlibs.CopyLibs.classpath="$GITHUB_WORKSPACE/lib/org-netbeans-modules-java-j2seproject-copylibstask.jar" \
            dist

      # ==========================================
      # 11. Check WAR
      # ==========================================
      - name: Check WAR file
        run: |
          ls -lh dist/
          test -f dist/WebGame.war

      # ==========================================
      # 12. Upload WAR artifact
      # ==========================================
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebGame-WAR
          path: dist/WebGame.war
    
      # ==========================================
      # Build Docker image
      # ==========================================
      - name: Build Docker image
        run: |
          docker build \
            -t webgame:${{ github.sha }} \
            -t webgame:latest \
            .

      # ==========================================
      # 13. Scan Docker image with Trivy
      # ==========================================
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'webgame:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'


      # ==========================================
      # 15. Login to GitHub Container Registry
      # ==========================================
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      # ==========================================
      # Set lowercase image name
      # ==========================================
      - name: Set image name
        run: |
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"

      # ==========================================
      # 16. Tag Docker image for GHCR
      # ==========================================
      - name: Tag Docker image
        run: |
          docker tag webgame:${{ github.sha }} \
            $IMAGE_NAME:${{ github.sha }}

          docker tag webgame:latest \
            $IMAGE_NAME:latest

      
      # ==========================================
      # 17. Push Docker image to GHCR
      # ==========================================
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest




    # ==========================================
  # 18. Test GHCR Authentication
  # ==========================================
  test-ghcr:

    name: Test GHCR Authentication

    runs-on: self-hosted

    steps:

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | \
            docker login ghcr.io \
            -u "${{ secrets.GHCR_USERNAME }}" \
            --password-stdin

      - name: Pull WebGame image
        run: |
          docker pull ghcr.io/moncrook/webgame-devops:latest

      - name: Check downloaded image
        run: |
          docker images ghcr.io/moncrook/webgame-devops


  # ==========================================
  # 19. Deploy WebGame to Ubuntu
  # ==========================================
  deploy:

    name: Deploy WebGame

    needs:
      - build-and-test
      - test-ghcr

    runs-on: self-hosted

    steps:

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | \
            docker login ghcr.io \
            -u "${{ secrets.GHCR_USERNAME }}" \
            --password-stdin

      - name: Pull latest WebGame image
        run: |
          docker pull ghcr.io/moncrook/webgame-devops:latest

      - name: Deploy with Docker Compose
        run: |
          cd /home/moncrook/webgame

          docker compose down

          docker compose up -d

      - name: Check deployment
        run: |
          cd /home/moncrook/webgame

          docker compose ps

      - name: Check WebGame logs
        run: |
          cd /home/moncrook/webgame

          docker compose logs webgame --tail=30

        