name: WebGame CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build-and-test:

    name: Build and Unit Test

    runs-on: ubuntu-24.04

    steps:

      # ==========================================
      # 1. Checkout source code
      # ==========================================
      - name: Checkout source code
        uses: actions/checkout@v4

      # ==========================================
      # 2. Setup JDK 21
      # ==========================================
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # ==========================================
      # 3. Install Ant
      # ==========================================
      - name: Install Ant
        run: |
          sudo apt-get update
          sudo apt-get install -y ant

      # ==========================================
      # 4. Setup Tomcat 10.1.57
      # ==========================================
      - name: Setup Tomcat 10.1.57
        run: |
          wget -q https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.57/bin/apache-tomcat-10.1.57.tar.gz
          tar -xzf apache-tomcat-10.1.57.tar.gz
          echo "CATALINA_HOME=$GITHUB_WORKSPACE/apache-tomcat-10.1.57" >> $GITHUB_ENV

      # ==========================================
      # 5. Check Java
      # ==========================================
      - name: Check Java version
        run: java -version

      # ==========================================
      # 6. Check Ant
      # ==========================================
      - name: Check Ant version
        run: ant -version

      # ==========================================
      # 7. Check Tomcat
      # ==========================================
      - name: Check Tomcat
        run: |
          echo "Tomcat home: $CATALINA_HOME"
          ls -la "$CATALINA_HOME"

        
      - name: Check NetBeans CopyLibs
        run: |
            ls -lh "$GITHUB_WORKSPACE/lib/"

      # ==========================================
      # 8. Clean project
      # ==========================================
      - name: Clean project
        run: |
            ant \
            -Dj2ee.server.home="$CATALINA_HOME" \
            -Dlibs.CopyLibs.classpath="$GITHUB_WORKSPACE/lib/org-netbeans-modules-java-j2seproject-copylibstask.jar" \
            clean

      # ==========================================
      # 9. Unit Test
      # ==========================================
      - name: Run unit tests
        run: |
            ant \
            -Dj2ee.server.home="$CATALINA_HOME" \
            -Dlibs.CopyLibs.classpath="$GITHUB_WORKSPACE/lib/org-netbeans-modules-java-j2seproject-copylibstask.jar" \
            test

      # ==========================================
      # 10. Build WAR
      # ==========================================
      - name: Build WAR
        run: |
            ant \
            -Dj2ee.server.home="$CATALINA_HOME" \
            -Dlibs.CopyLibs.classpath="$GITHUB_WORKSPACE/lib/org-netbeans-modules-java-j2seproject-copylibstask.jar" \
            dist

      # ==========================================
      # 11. Check WAR
      # ==========================================
      - name: Check WAR file
        run: |
          ls -lh dist/
          test -f dist/WebGame.war

      # ==========================================
      # 12. Upload WAR artifact
      # ==========================================
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebGame-WAR
          path: dist/WebGame.war
    
      - name: Build Docker image
        run: |
          docker build \
            -t webgame:${{ github.sha }} \
            -t webgame:latest \
            .

       # ==========================================
      # 13. Scan Docker image with Trivy
      # ==========================================
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'webgame:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'